### ISSUE TITLE
crash vc2019

### ISSUE THREAD

**Issue by r-lyeh** [mattiasgustavsson/blast_tracker#1]
![image](https://user-images.githubusercontent.com/35402248/77226497-196cd880-6b79-11ea-8ad3-2c9eb4fb1e98.png)

also, missing link #pragma comment(lib, "comdlg32") for  __imp_GetOpenFileNameA / __imp_GetSaveFileNameA

**Comment by mattiasgustavsson** [comment]
I think I didn’t upload the soundfont, that’s why it’s crashing. You can find it in several places on the net, here’s one https://musical-artifacts.com/artifacts/15

And this is very much a wip - but thanks for finding the comdlg32 issue, I’ll fix that.

**Comment by r-lyeh** [comment]
ah cool, didnt see the sf2 loading. suggestion:

```C
tsf* soundfont = tsf_load_filename( "OPL-3_FM_128M.sf2" );
//    tsf* soundfont = tsf_load_filename( "1MGM.sf2" );
if(!soundfont) exit(-puts("cannot load OPL-3_FM_128M.sf2" ));
```

**Comment by mattiasgustavsson** [comment]
Oh for sure, there’s basically no error handling whatsoever yet, needs adding everywhere :p
